export const FETCH_USER_MANAGEMENT_SUCCESS = "FETCH_USER_MANAGEMENT_SUCCESS";
export const FETCH_USER_MANAGEMENT_FAIL = "FETCH_USER_MANAGEMENT_FAIL";

export const FETCH_ADD_USER_SUCCESS = "FETCH_ADD_USER_SUCCESS";
export const FETCH_ADD_USER_FAIL = "FETCH_ADD_USER_FAIL";

export const FETCH_EDIT_USER_SUCCESS = "FETCH_EDIT_USER_SUCCESS";
export const FETCH_EDIT_USER_FAIL = "FETCH_EDIT_USER_FAIL";

export const FETCH_DELETE_USER_SUCCESS = "FETCH_DELETE_USER_SUCCESS";
export const FETCH_DELETE_USER_FAIL = "FETCH_DELETE_USER_FAIL";
