// export const FETCH_MOVIE_INFOR_SUCCESS = "FETCH_MOVIE_INFOR_SUCCESS"
// export const FETCH_MOVIE_INFOR_FAIL = "FETCH_MOVIE_INFOR_FAIL"



export const FETCH_ALL_MOVIE_SUCCESS = "FETCH_ALL_MOVIE_SUCCESS";
export const FETCH_ALL_MOVIE_FAILED = "FETCH_ALL_MOVIE_FAILED";
export const FETCH_ALL_MOVIE = 'FETCH_ALL_MOVIE';

export const SET_SHOWTIME_THEATER_SYSTEM = "SET_SHOWTIME_THEATER_SYSTEM";
