export const FETCH_ALL_MOVIE_SUCCESS = "FETCH_ALL_MOVIE_SUCCESS";
export const FETCH_ALL_MOVIE_FAILED = "FETCH_ALL_MOVIE_FAILED";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const PHIM_DANG_CHIEU = "PHIM_DANG_CHIEU"
export const PHIM_SAP_CHIEU = "PHIM_SAP_CHIEU"