export const FETCH_MOVIE_MANAGER_RESQUESS = "FETCH_MOVIE_MANAGER_RESQUESS"
export const FETCH_MOVIE_MANAGER_SUCCESS = "FETCFETCH_MOVIE_MANAGER_SUCCESSH_"
export const FETCH_MOVIE_MANAGER_FAIL= "FETCH_MOVIE_MANAGER_FAIL"
