export const FETCH_MOVIE_DETAIL_SUCCESS = "FETCH_MOVIE_DETAIL_SUCCESS";
export const FETCH_MOVIE_DETAIL_FAIL = "FETCH_MOVIE_DETAIL_FAIL"

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";